### ISSUE TITLE
Implementar estrutura HTML do Editor de Cordeis

### ISSUE THREAD

**Issue by CarlosJSL** [encantando-cordel/encantando-web#2]

**Comment by sarahraquel** [comment]
![screen shot 2018-11-07 at 14 46 55](https://user-images.githubusercontent.com/14362964/48149879-074c0c00-e29c-11e8-9288-b66e37190b8e.png)

**Comment by 3w3rt0n** [comment]
Foi refeito a estrutura do HTML do editor, devido a alterações no layout.
