### ISSUE TITLE
Deixar texto e título do editor editável novamente 

### ISSUE THREAD

**Issue by sarahraqueld** [encantando-cordel/encantando-web#42]
O PR https://github.com/encantando-cordel/encantando-web/pull/26 removeu a habilidade do usuário de adicionar texto no editor de cordeis. Adicionar novamente.

**Comment by 3w3rt0n** [comment]
Removido temporariamente enquanto estava sendo definido as posições corretas pelo design, já foi incluído novamente no layout final.
